### ISSUE TITLE
Need to security validate decompression of files...

### ISSUE THREAD

**Issue by JustinCappos** [theupdateframework/tuf#105]
Can someone create a series of tests where the compressed file unpacks to a different dir or has an unexpected name?   

We should block these cases.

We also should consider how / why we can argue that the compression library is unlikely to result in a buffer overflow or similar vulnerability.   In the interim, perhaps it is a good idea to have an option to disable compression for TUF clients.

**Comment by heartsucker** [comment]
I've run into this question right now. I'm don't like the idea that metadata is allowed to be compressed for the same reason that you mentioned above, possible vulnerabilities in the decompression library. I would rather not support compression if it's left in its current form. Tagging @brson since this is relevant to our email discussion.

On a similar note, if compressed images want to be served, they' have to be listed as two different targets which makes dependency management a bit annoying.

This is my proposal.

1. Root and timestamp metadata are never compressed
2. All other metadata may be compressed, but their entries in timestamp/snapshot need to include hashes/size of the actual image and all compressed versions
3. Images may be compressed, but their entries in targets/delegations need to include hashes/size of the actual images and all compressed versions.
4. Downloaded files are not streamed through the decompressor but written to disk (up to `size` for compressed file). The compressed file is validated (`hash`). They are decompressed up to `size` for the plain image. The decompressed file is validated (`hash`). Then it's passed on to the application.

The size for the decompressed data must be known to prevent the case of tar-bombs filling the disk on decompression.

For example, it would look something like this:

```json
"some/target": {
  "size": 1234,
  "hashes": {
    "sha256": "abcdef01234"
  },
  "compressed": {
     "tar.gz": {
       "size": 456,
       "hashes": {
          "sha256": "1234dcba"
       }
   }  
}
```

**Comment by vladimir-v-diaz** [comment]
This issue is no longer relevant due to the acceptance and implementation of [TAP 10](https://github.com/theupdateframework/taps/blob/master/tap10.md) (Remove native support for compressed metadata).
