### ISSUE TITLE
Design client library

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1135]
Identify what functionality from existing updater/download modules should exist in a TUF client on top of a metadata model as sketched in #1112. 

Start with API functionality.

Coordinate with #1134.

**Comment by joshuagl** [comment]
Things to consider, based on learnings from a PoC integration with pip (cc @jku):
* ~download progress reporting #1057~ handled with the abstract `Fetcher` interface https://github.com/theupdateframework/tuf/pull/1250
* ~allowing a package manager to plug-in their own network/download stack~ resolved with the abstract `Fetcher` interface https://github.com/theupdateframework/tuf/pull/1250
* minimal footprint (minimal dependencies and being able to be installed independently of the repository library and tools)
* supporting metadata and targets on separate hosts, and different targets on different hosts #1143 
* ability to check for existence of local configuration for a given repository #1063

TAPs to be aware of when designing:
* [TAP 3: Multi-role delegations](https://github.com/theupdateframework/taps/blob/master/tap3.md) – accepted, but not in the specification because it is not implemented for the reference implementation
* [TAP 4: Multiple repository consensus on entrusted targets](https://github.com/theupdateframework/taps/blob/master/tap4.md) – accepted, but not yet in the specification. Implemented in the current reference implementation

**Comment by jku** [comment]
> * allowing a package manager to plug-in their own network/download stack

Filed #1142 for this

**Comment by jku** [comment]
> * supporting metadata and targets on separate hosts, and different targets on different hosts

and  #1143 for this

**Comment by jku** [comment]
See #1158 for "client/updater: Parallel Downloads"

**Comment by joshuagl** [comment]
We're seeing multiple areas where the current Updater interface/API is brittle or confusing (#1143, #1174, possibly others).

I had originally expected that we would try to maintain the current updater API, but we should review that and even if we do stay close to the current API plan to fix the confusing/outdated/inflexible aspects.

**Comment by jku** [comment]
> I had originally expected that we would try to maintain the current updater API, but we should review that and even if we do stay close to the current API plan to fix the confusing/outdated/inflexible aspects.

Same same.

Now that we've kicked out mirrors (so are not directly compatible anyway) and now that I've had time to think about it, I think we should improve the API as much as we can. It'll still be quite close to the old one (so not hard to port) but hopefully an improvement.

Latest ideas in https://github.com/theupdateframework/tuf/issues/1317#issuecomment-843872644

**Comment by MVrachev** [comment]
I think that in a way this issue and issue #1317 are covering the same stuff.
Do we need that one?
If we don't, I think the only two proposals left that are not addressed are 

> TAPs to be aware of when designing:

- [TAP 3: Multi-role delegations](https://github.com/theupdateframework/taps/blob/master/tap3.md) – accepted, but not in the specification because it is not implemented for the reference implementation
- [TAP 4: Multiple repository consensus on entrusted targets](https://github.com/theupdateframework/taps/blob/master/tap4.md) – accepted, but not yet in the specification. Implemented in the current reference implementation

which we can move in #1317 as TODO items.

**Comment by jku** [comment]
IMO the final missing piece(s) here might be documented in #1580.

**Comment by jku** [comment]
I'm sure there are features that are still wanted by someone, but I think the client design is now done and implemented: anything still missing is a new feature, closing this one
