### ISSUE TITLE
Review cryptography

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#119]
We need to review the cryptography used in TUF.

In particular, I need to review the cryptography decisions that @vladimir-v-diaz has made while adopting PyCrypto.

Furthermore, we need to review the specific cryptographic techniques adopted by TUF to ensure that it is reasonably future-proof. We need to understand what the cryptographers recommend in light of recent news.

* [The NSA Is Breaking Most Encryption on the Internet](https://www.schneier.com/blog/archives/2013/09/the_nsa_is_brea.html)
* [The NSA's Cryptographic Capabilities](https://www.schneier.com/blog/archives/2013/09/the_nsas_crypto_1.html)
* [Matthew Green Speculates on How the NSA Defeats Encryption](https://www.schneier.com/blog/archives/2013/09/matthew_green_s.html)

**Comment by Ayrx** [comment]
(Disclaimer, I work on [pyca/cryptography](https://github.com/pyca/cryptography/))

Given that the PyCrypto project isn't in active development anymore, will you be willing to merge a PR to prefer pyca/cryptography over PyCrypto? It should support all the required algorithms provided by PyCrypto that tuf uses as of now.

Some benefits pyca/cryptography has over PyCrypto:

1. Supports PyPy.
2. Uses OpenSSL (by default) instead of a custom C library. Say what you will about OpenSSL but it's probably the most battle-tested crypto library out there.
3. Active development with support for more modern algorithms coming up which may or may not interest  the tuf project.

**Comment by vladimir-v-diaz** [comment]
Supporting pyca/cryptography was on our TODO list for PEP 458.  We would certainly be willing to merge a PR to support this library!

**Comment by Ayrx** [comment]
@vladimir-v-diaz Look out for one sometime this week then. :)

**Comment by vladimir-v-diaz** [comment]
Awesome.  Adding support for `pyca/Cryptography` should be relatively straightforward, but feel free to contact us if you have any questions.

A single `pyca/Cryptography` module should be the only addition required, similar to:
[ed25519_keys.py](https://github.com/theupdateframework/tuf/blob/develop/tuf/ed25519_keys.py) and [pycrypto_keys.py](https://github.com/theupdateframework/tuf/blob/develop/tuf/pycrypto_keys.py)

The minor changes will be to configuration settings: https://github.com/theupdateframework/tuf/blob/develop/tuf/keys.py#L77-L81.

If you wish `pyca/Cryptography` to be the default general purpose crypto library: https://github.com/theupdateframework/tuf/blob/develop/tuf/conf.py#L92-L98

**Comment by Ayrx** [comment]
@vladimir-v-diaz As part of implementing support for pyca/cryptography, are you opposed to a refactor of the crypto APIs to make things more easily pluggable?

For example, I have noticed that much of the code in the `encrypt()` and `decrypt()` functions can be reused, only the library-specific code (mostly found in private functions like `_encrypt()`) needs to be changed.

I have in mind an interface implemented with python's [abc](https://docs.python.org/2/library/abc.html) module that enforces a public API. 

It's slightly more work than just copying bits of code between implementations but it's a cleaner solution in the long run I think. If this is something you agree with I'll be willing to write the code to make it work. :)

**Comment by vladimir-v-diaz** [comment]
We would rather avoid abstract classes, metaclasses, and OOP here.  Some of our crypto modules previously used an object-oriented design and were refactored to use a procedural approach instead; we found the previous design lacked in readability.  Furthermore, adding support for other libraries should be a rare occurence; `pyca/cryptography` and `pycryptopp` are probably the only libraries that are going to be added in the near future.  It is ideal for these libraries to be supported directly in the code and available to others.

Are you referring to [encrypt_key()](https://github.com/theupdateframework/tuf/blob/develop/tuf/pycrypto_keys.py#L657-L686)?  That function is approximately five lines of code if you remove the documentation; we don't mind duplicating these lines.  You may even put library-specific code in encrypt_key() if desired, `pycrypto_keys.py` happens to make the external library calls in _encrypt() to keep functions small.

You are also free to choose the names of the functions in `pycacrypto_keys.py`, as they will be directly called in `keys.py`.  For example: https://github.com/theupdateframework/tuf/blob/develop/tuf/keys.py#L1143-L1153.  Personally, I prefer direct and explicit calls like these, rather than indirectly through objects.  However, I do see the usability gain of an OO design for user-facing APIs.  We may even add a class for a user-facing API if we decide in the future that the crypto side should be exentisible.

Note: These crypto modules are heavily documented, but `ed25519_keys.py` is about 60 lines of code and `pycrypto_keys.py` 158.  `pycacrypto_keys.py` will likely be within this range.

**Comment by vladimir-v-diaz** [comment]
@Ayrx
Did you get a chance to work on this PR?  I can pick up from where you left off if you are currently busy with other projects.

**Comment by Ayrx** [comment]
@vladimir-v-diaz I only got this partially (very little actually) done since I got caught up with some other stuff. Sorry. :)

**Comment by vladimir-v-diaz** [comment]
No worries.

**Comment by kalefranz** [comment]
To the community's knowledge, is anybody currently working on this? Or is it again up for grabs?

**Comment by vladimir-v-diaz** [comment]
That's correct, this feature request was implemented in #289.  We are currently reviewing it and will close this issue once the implementation has been fully reviewed.

**Comment by sirlatrom** [comment]
If #289 is merged, why is this issue still open?

**Comment by vladimir-v-diaz** [comment]
We forgot to close this issue after reviewing #289.  Closing this now.  Thanks!

**Comment by sirlatrom** [comment]
@vladimir-v-diaz Great, it stood out on the mobile version of the repo's front page, that's how I got here
