### ISSUE TITLE
GitHub Actions: Consider hardening setup against CVE-2020-15228

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1246]
**Description of issue or feature request**:
#1242 added a GitHub Actions based CI workflow . GitHub Actions has a moderate injection vulnerability (CVE-2020-15228) against which we should consider hardening our setup.

**Current behavior**:
No particular hardening against CVE-2020-15228

**Expected behavior**:
Assess necessity and harden against CVE-2020-15228.

@jku proposes a strategy in https://github.com/theupdateframework/tuf/issues/1195#issuecomment-744600836 also described in https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by joshuagl** [comment]
Additional hardening we might consider is in  the actions we use.

AFAICT an Action release on the marketplace corresponds to a tag in the repository that publishes the action, which leaves users open to malicious maintainer attacks - tags are not immutable, so a repo owner (or attacker) can replace the tag and point to a malicious version of the action.

GitHub allows us to restrict actions to either: only use actions defined in our org, only allow a predefined list of actions, or allow all actions.

**Comment by lukpueh** [comment]
Good observation, @joshuagl! Here are some ideas to reduce the attack surface:

- [use the commit sha](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/finding-and-customizing-actions#using-shas) instead of the tag (with the downside of pinning full versions, whereas with tags you can also pin major or minor only)
- allow [only actions created/hosted by GitHub](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#allowing-specific-actions-to-run) (and maybe popular verified 3rd-party actions)
- try to use custom shell scripts on the [`run:` keyword](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun) instead of non-verified 3rd-party actions where feasible

**Comment by trishankatdatadog** [comment]
You guys are really thinking this through. Very impressive! 👏🏽

**Comment by joshuagl** [comment]
Another reason to distrust 3rd-party Actions – they can push commits (and tags?) to the repository[[1](https://hikari.noyu.me/blog/2020-05-05-github-private-repos-access-control-violation.html)].

Furthermore, possibly due to the underlying shared object storage of GitHub, it seems that git activity on forks __may__ have unintended consequences on the forked repo. So far as I can tell, this is not yet confirmed, but the Caddy Web Server seems to have had a release made – and pushed to the Go module proxy – by a tag being pushed to a fork of their repo[[2](https://twitter.com/caddyserver/status/1338324879167275008/)].

**Comment by joshuagl** [comment]
GitHub's Security Lab have published some research and recommendations on securing GitHub Actions workflows:
* [Keeping your GitHub Actions and workflows secure: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests)
* [Keeping your GitHub Actions and workflows secure: Untrusted input](https://securitylab.github.com/research/github-actions-untrusted-input)

Haven't had chance to dig into this at all, but found an experiment in "Verifiable GitHub Actions" [verifyme](https://github.com/dlorenc/verifyme)

**Comment by jku** [comment]
I'd like to close this:
* the specific issue that started it has been fixed by github (add-path and set-env commands no longer exist)
* I've spent time looking at Github actions and have come up with two minor improvements: #1662 and #1652. otherwise the setup seems solid to me
* using tags for actions does sound a little fishy -- but for the official github actions it seems reasonable: we've made the decision to trust github so we trust their tags to point to right places as well
* verifying the build environment and making it auditable sounds potentially interesting but I think it should not be handled in this issue: please file specific issues if you think there's something we should do 

That leaves us with (I think) just some configuration, like _allow only actions created/hosted by GitHub_: I think this makes sense since we currently only use githubs own actions (and should have a high bar for using actions made by others). Would one of the org admins like to make that call and maybe flick the switch in settings?

**Comment by lukpueh** [comment]
> Would one of the org admins like to make that call and maybe flick the switch in settings?

Done!

Thanks for the research and for creating two more specific issues. Closing..
