### ISSUE TITLE
Use lazy (old style %-format) log formatting in the new pylint config

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1334]
**Description of issue or feature request**:
Using f-strings (and all types of string formatting except %-syle) in logging messages is not lazy evaluated so linters "recommend" %-style formatting.

Should we disable the related pylint warnings and use f-strings:
```
logging-not-lazy
logging-format-interpolation
logging-fstring-interpolation
```
or adhere to the recommendation.

**Current behavior**:
Top-level `pylintrc` disables logging that recommend lazy formatting globally.
New `api/pylintrc` does not.

**Expected behavior**:
Decide on a common approach.

**Comment by sechkova** [comment]
An example approach to avoid the warnings while using f-strings which feels more like a workaround: 438c0a0

**Comment by jku** [comment]
It's annoying to use a different formatting method for logging than anything else but the reasoning is solid... Most of our logging is not in a "hot loop" but some debug logs really might be used quite a lot (and the workaround only hides the warning, not the potential performance issue in those cases).

I think using %-style is fine for logging: `logger.debug("processing, a=%s", a)` but it's not a strong opinion -- in the opposite case we may want to do a quick review to identify hottest logging calls though.

**Comment by sechkova** [comment]
And then there is [this issue](https://github.com/PyCQA/pylint/issues/3362) when trying to use %-style formatting but you've set up `pylint` to `logging-format-style=new`.

**Comment by jku** [comment]
I had understood that using %-style implies means we would need to use `logging-format-style=old` anyway (or rather not set it as that's the default)? Pylint docs really could have more examples.

**Comment by jku** [comment]
I'm proposing we use the default logging style, meaning: 
* use `logging-format-style=old` (which is default value)
* stop disabling `logging-not-lazy` (note: this is done only in some experimental client branches -- metadata api itself hasn't needed this because there's zero logging so far :grimacing: )

It looks a bit uglier (other string formatting is f-strings but logging is then based on %-formatting) but:
* it's a common style
* it's suggested by the google style guide
* it means we don't have to think about performance when writing logging code

**Comment by joshuagl** [comment]
Proposal above makes sense to me, if it's what's suggested by the style guide we probably don't even need to capture anything for this? Let's just do what our style guide suggests.
