### ISSUE TITLE
review metadata api docstrings before release

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1357]
This came up in #1354: let's check that our api docstrings are consistent -- the specific case was "Optional" in the docstring:
```
        Arguments:
            data: metadata content as string.
            deserializer: Optional; A MetadataDeserializer instance that...
```
This is from a google style guide example and is used when the argument has a default value (not when the argument is a `Optional[T]`).

**Comment by MVrachev** [comment]
In pr #1329 linting failed for file `tuf/api/metadata.py` because of the "C0302: Too many lines in module" warning which warns for modules
with more than 1000 lines.

This is a good reminder that probably our comments are too lengthy.
@jku could you add a todo item to try to shorten our docstrings to this issue?

**Comment by MVrachev** [comment]
@jku do you think we need another look at the Metadata API docstrings after the revisions you made in https://github.com/theupdateframework/tuf/pull/1456

**Comment by jku** [comment]
There's a lot to improve (#1543) but I think we shouldn't block a release on any of the docstring changes...
