### ISSUE TITLE
Metadata API: validate that "paths" or "path_hash_prefixes" is set

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1497]
**Description of issue or feature request**:
As @sechkova  have pointed out in this comment https://github.com/theupdateframework/tuf/pull/1463#issuecomment-875745034 in `DelegatedRole` we are checking if `paths` and `path_hash_prefixes` BOTH are set, but we aren't checking
if at least one of them is set:
https://github.com/theupdateframework/tuf/blob/24fa1128116429dc18e185047fbffb009ca509b0/tuf/api/metadata.py#L914

For more context read https://github.com/theupdateframework/specification/issues/156.

**Current behavior**:
We don't check if BOTH `paths` and `path_hash_prefixes` are None.

**Expected behavior**:
Check if BOTH `paths` and `path_hash_prefixes` are None.

**Comment by jku** [comment]
I don't think there's a clear consensus that that is the expected behaviour https://github.com/theupdateframework/specification/issues/156 


I thought `paths=None, path_hash_prefixes=None` was legal and means "I want to delegate everything" as otherwise that wouldn't be possible at all (well `path_hash_prefixes=[""]` probably would delegate everything but seems even more like a hack). I don't think there's much in the spec to support either stance.

**Comment by joshuagl** [comment]
Let's implement something which replicates the behaviour of the current client until the specification better defines what is expected.

**Comment by sechkova** [comment]
> Let's implement something which replicates the behaviour of the current client until the specification better defines what is expected.

Done with 2159b88.

**Comment by sechkova** [comment]
76d46336007ef9a6974b5ef3e6bac7e3a62924f6 which replicates current client behaviour is merged so until the issue in the specification gets resolved, the client raises an error if none of paths and path_hash_prefixes is set. 

Closing this issue and will reopen if an update of the code is needed to conform to the spec.
