### ISSUE TITLE
Metadata API: prevent Delegation role names to be one of top level metadata roles

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1558]
**Description of issue or feature request**:

**Current behavior**:
Delegation role names are not restricted in any way in the spec, but they are targets metadata role names.
That could lead to a problem if delegation role names are one of `root`, `timestamp`, `snapshot` or `targets`.

**Expected behavior**:
Make sure that delegation role names aren't one of the top-level metadata roles.

**Comment by joshuagl** [comment]
I wonder if this kind of logic and role name sanitisation more generally belongs in metadata API? Perhaps it should be part of the (as yet undesigned) repository interface?

**Comment by jku** [comment]
same check does make sense in a client: we would not want to accidentally overwrite our local root.json because a targets decides to delegate to a "root" role version 9000.

I don't think there are practical risks of that -- the client would have to succeed in downloading and verifying the file _as a targets metadata_ before it would be written to local disk but this still seems like a reasonable check for a client to make

**Comment by jku** [comment]
the legacy client also prevents empty string as rolename -- this seems like  a reasonable take for ngclient too

**Comment by joshuagl** [comment]
@MVrachev is this issue covered by https://github.com/theupdateframework/python-tuf/pull/1630?

**Comment by MVrachev** [comment]
No, as the validation itself happens in the delegator class who have the full list of roles or in the case of #1630 that's `Root`.
Here the validation should happen in `Targets` the same way it's done in #1630.

**Comment by MVrachev** [comment]
When solving this issue please add tests in `test_metadata_serialization.py` the same way it's done in #1630 specifically see `incorect_roots`.

**Comment by kairoaraujo** [comment]
I am working on this issue.
