### ISSUE TITLE
https://github.com/faisalman/ua-parser-js/issues/536

### ISSUE THREAD

**Issue by nathanawmk** [theupdateframework/tuf#1632]
I refer to the following massive security incident relating to compromised npm:

1. https://us-cert.cisa.gov/ncas/current-activity/2021/10/22/malware-discovered-popular-npm-package-ua-parser-js 
2. https://github.com/faisalman/ua-parser-js/issues/536

I am thinking of enhancing/leveraging TUF to secure NPM so such security incident won't happen again. Would the use of TUF stopped such attack?

**Comment by mnm678** [comment]
TUF is able to catch when a package is uploaded by someone other than the maintainer of that package, because the package would not have the correct signature. It looks like that is what happened here. TUF is also able to revoke a key in the event that the key is compromised by an attacker or used by a malicious maintainer.

I'd be happy to discuss integrating TUF into NPM. Are you a developer on the NPM project?

**Comment by jku** [comment]
> Would the use of TUF stopped such attack?

There's not enough details about the incident to be sure, but using TUF certainly gives maintainers and repositories a much wider array of methods to prevent this sort of issues.

If you'd like to talk about integrating TUF into an ecosystem, I would suggest 
* slack: https://cloud-native.slack.com/channels/tuf
* email list: https://groups.google.com/forum/?fromgroups#!forum/theupdateframework

(This is the issue tracker for the python implementation: more people are going to see the posts in those places)

**Comment by jku** [comment]
closing this: it does not seem to be an issue with python-tuf
