### ISSUE TITLE
Version 1.0 release strategy

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf#1645]
We have a loosely communicated intent to ship python-tuf 1.0 with only the new/refactored code (metadata API + ngclient + ???). We should define what that release looks like, including accounting for:

- Communicating deprecation expectations with regards the legacy code
  - [ADR 2](https://github.com/theupdateframework/python-tuf/blob/develop/docs/adr/0002-pre-1-0-deprecation-strategy.md) indicates legacy code will be supported on a best-effort basis, but this has not been communicated to users of python-tuf
  - > "Support for older releases: Bugs reported with tuf versions prior to 1.0.0 will likely not be addressed directly by tuf’s maintainers. Pull Requests to fix bugs in the last release prior to 1.0.0 will be considered, and merged (subject to normal review processes). Note that there may be delays due to the lack of developer resources for reviewing such pull requests."
- What the feature complete state looks like for a python-tuf 1.0 release? Must python-tuf 1.0 provide feature parity with the legacy code?

**Comment by lukpueh** [comment]
This is a list of items that I think should and are feasible to be in 1.0.0 by the tentatively scheduled release date end of 2021 / early 2022, plus a rough list of TODO items to get to 1.0.0. Feel free to comment, add, remove and help break down the items in both lists.

### Feature set of 1.0.0
- feature complete client
- client API docs on [RTD](https://theupdateframework.readthedocs.io/en/latest/api/tuf.ngclient.html) (`#1595, #1601`)
- client tutorial/example (`#1518`)
- metadata API
- metadata API docs on [RTD](https://theupdateframework.readthedocs.io/en/latest/api/tuf.api.html) (`#1600, #1595, #1602`)
- no repository tool
  *NOTE: It is not feasible to have a stable repository tool by the planned 1.0.0 release date. I suggest we publicly express our intent to provide one post-1.0.0, and until then provide example code that uses the metadata API for all repo activities.*
- repository tutorial/example based on metadata API
  *NOTE: The main usage scenarios are described in the [advanced tutorial](https://github.com/theupdateframework/python-tuf/blob/develop/docs/TUTORIAL.md) and in [this usage scenario draft document](https://docs.google.com/document/d/1qBNR-_HuS312H9YjFdIbll8MW8Abe9ORYzx43z-bpEk). Plus the [repo editor](https://github.com/vmware-labs/repository-editor-for-tuf) demonstrates how to use the metadata API for this purpose (its generic UI aspect may be ignored).*
- no legacy code
- 1.0.0 release announcement plus migration document with the following contents:
  - planned 1.0.0 release date
  - link to ADR 2 and the fact that pre-1.0.0 code will remain available and be supported on a best-effort basis
  - list of what will be in 1.0.0 and what won't (basically this list)
  - links to client example code and repository tutorial (see corresponding items above)
  - an explanation how a generic from-legacy-to-new migration guide is not feasible, due to varying TUF usage
  - our word that we are contacting our users individually to help them migrate
  - an offer to all our users that we haven't contacted, to reach out to us so that we can help them migrate

### TODO:
- review/create/associate/resolve issues for items above, maybe re-use 1.0.0 GitHub project to manage?
- publish 1.0.0 announcement/migration guide soon
- post link to 1.0.0 announcement/migration guide on slack, mailing list, theupdateframework.io and on top of python-tuf#README
- contact known adopters individually and offer help

**Comment by joshuagl** [comment]
There were a couple of items on my "before 1.0" bucket list:
- move to automated (SLSA compliant) release builds prior to 1.0 (#1550)
- figure out how to keep in synch with the spec and better indicate current spec compliance (#1598)

**Comment by lukpueh** [comment]
adding more issues to the bucket list, based on my suggestions from above...

- #1518
- #1673
- #1676
- #1627
- #1600
- #1595

**Comment by MVrachev** [comment]
More issues on the bucket list from me:
- #1638
- #1646
- #1575
- #1602
- #1729
- #1727
- #1312
- #1764

**Comment by jku** [comment]
Probably:
* https://github.com/theupdateframework/python-tuf/issues/1634

**Comment by MVrachev** [comment]
As a TODO item:
- [ ] have a look into the specification to figure out which version of it the specification the new code actually supports

**Comment by joshuagl** [comment]
> As TODO items:
> 
> * [ ]  have a look into the specification to figure out which version of it the specification the new code actually supports

Relates to https://github.com/theupdateframework/python-tuf/issues/1598

**Comment by jku** [comment]
Lukas just created a [1.0.0 blockers](https://github.com/theupdateframework/python-tuf/labels/1.0.0%20blockers) label. Let's agree on some rules though... my suggestion:
* anyone (with label permissions) can add/remove issues to label, or suggest additions here
* when issues are added/removed, they should be announced in a comment here so others are notified

we should aim to only include things that are _required_ to get 1.0 released -- fixing other things is still ok but they don't need the label.

**Comment by jku** [comment]
* Added blocker #1763

**Comment by MVrachev** [comment]
> More issues on the bucket list from me:
> 
> * [ngclient: review argument names #1638](https://github.com/theupdateframework/python-tuf/issues/1638)
> * [metadata API: avoid raising securesystemslib exceptions #1646](https://github.com/theupdateframework/python-tuf/issues/1646)
> * [ngclient: should clean temp file if write fails #1575](https://github.com/theupdateframework/python-tuf/issues/1575)
> * [metadata API: TargetFile.custom is not visible in documentation #1602](https://github.com/theupdateframework/python-tuf/issues/1602)
> * [What to do with tuf/exceptions before 1.0.0? #1729](https://github.com/theupdateframework/python-tuf/issues/1729)
> * [Metadata API: rethink the expiry related API #1727](https://github.com/theupdateframework/python-tuf/issues/1727)
> * [review/document client exceptions #1312](https://github.com/theupdateframework/python-tuf/issues/1312)
> * [Review all TODO items in the new implementation prior to 1.0.0 #1764](https://github.com/theupdateframework/python-tuf/issues/1764)

I am going to label the yet unresolved issues from my list as `blockers`.

**Comment by jku** [comment]
Added (ngclient) exceptions tweaks as blockers:
* #1761
* #1714

**Comment by jku** [comment]
I'd really like these... but maybe not release blockers in the end? @joshuagl opinions?
* #1550, #1269
* #1756

Added as blocker:
* #1634
* #1739
* #1745 <- this one is big and should be started and split into parts ASAP: getting docs etc in order might take a while

**Comment by jku** [comment]
This one I think we should work on at least far enough that we know how it's going to be solved: if Metadata API does not break as result, it could wait until after 1.0? 
* #1696

**Comment by jku** [comment]
Opinions on this -- maybe should be in 1.0?
* #1251

EDIT: Added as blocker

**Comment by joshuagl** [comment]
> I'd really like these... but maybe not release blockers in the end? @joshuagl opinions?
> 
> * [Automated release builds #1550](https://github.com/theupdateframework/python-tuf/issues/1550), [Verifiably reproducible build artefacts #1269](https://github.com/theupdateframework/python-tuf/issues/1269)
> * [ngclient: Test against other implementations #1756](https://github.com/theupdateframework/python-tuf/issues/1756)

Agreed. These are important and nice to have for 1.0 but not blockers.
