### ISSUE TITLE
ngtests: add tests toggling consistent snapshot

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1667]
**Description of issue or feature request**:
Currently different configurations of `consistent_snapshot`, `prefix_targets_with_hash`  are tested in `test_updater_ng.py` which uses pre-generated test files.

After adding support for non-consistent snapshot #1637, analyze what would be meaningful consistent snapshot tests that preferably don't duplicate the tests code for each config and implement them using `RepositorySimulator`.

**Comment by jku** [comment]
> After adding support for non-consistent snapshot #1637, analyze what would be meaningful consistent snapshot tests that preferably don't duplicate the tests code

Sounds good.
I think it's reasonable to concentrate testing on
* consistent_snapshot with consistent targets
* consistent_snapshot without consistent targets (the special case for warehouse)

and leave the non-consistent_snapshot case with just the minimum tests to verify it works: everyone _should_ be using consistent_snapshot, we only support the other case because the spec still allows it.
