### ISSUE TITLE
docs: Remove AUTHORS.txt (or make it up-to-date)

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1807]
The intent to credit contributors is admirable but the file is outdated and does not really give us a lot of value over `git shortlog -s`.  I also do not think the file helps in tracking authorship since the file provides no information about what people authored.

Admittedly the file is better formatted than shortlog output... but if the file is not up to date then that does not help.

**Comment by lukpueh** [comment]
AUTHORS.txt (and the [acknowledgement section in the main README](https://github.com/theupdateframework/python-tuf/blame/b2704a56a8c5023ffd7d377d8a8e72fb26a46a8a/README.md#L130-L132)) has a few names that aren't in `git shortlog`, because 
- their involvement predates the use of `git` for python-tuf development, or
- they contributed to a TUF subproject other than python-tuf (e.g. notary, etc.)

I suggest to
1. update the acknowledgement section in README.md (or replace it with a dedicated acknowledgements document) that lists all significant and no longer active contributors and maintainers of python-tuf, which we should keep up-to-date (see #1793), optionally with their organization affiliation
2. maybe do something similar for the TUF organization (for the lack of a `theupdateframework/community` repo, it could be part of theupdateframework.io),
3. remove AUTHORS.txt in this repo

**Comment by lukpueh** [comment]
@JustinCappos, would you mind weighing in on what to do with the [AUTHORS.txt](https://github.com/theupdateframework/python-tuf/blob/0b64056ca48fa8e95e81c2272cba13c2eab76c86/docs/AUTHORS.txt) document?

**Comment by JustinCappos** [comment]
I am in favor of the approach you suggest @lukpueh .  Does anyone object?

**Comment by joshuagl** [comment]
No objections. 

From an implementation perspective, reproducible-builds.org contributor page lists everyone who touched the repo plus explicitly named personnel. We might create a similar script for listing TUF contributors on theupdateframework.io? See https://salsa.debian.org/reproducible-builds/reproducible-website/-/blob/master/bin/contributors.sh
