### ISSUE TITLE
unrecognized_fields is annotated as Mapping but maybe should be just Dict

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1938]
I'm pretty sure I suggested annotating unrecognized_fields as a Mapping (so "immutable dict") at some point. I was probably thinking about the client use case but clearly in the repository case this annotation can be incorrect: we may actually want to modify the content.

`unrecognised_fields` throughout the API (tuf/api/metadata.py) should be annotated as Dict.

**Comment by abs007** [comment]
Hi @jku I modified the code but could you guide me as to how I should be writing the tests and doc for this bug fix? Thanks

**Comment by lukpueh** [comment]
> Hi @jku I modified the code but could you guide me as to how I should be writing the tests and doc for this bug fix? Thanks

Thanks for the PR, @abs007! You don't need to add tests or write docs for this issue. But we require contributors to sign off their commits (see note about DCO in [contributor instructions](https://theupdateframework.readthedocs.io/en/latest/CONTRIBUTING.html#dco)) . I also suggest you to take a look at the [development guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md) linked from our contribution instructions, it has some good recommendations about commit messages.

**Comment by abs007** [comment]
@lukpueh I added new commits with the sign into #1949 but I think that won't work as expected because I originally made changes on the develop branch itself, so I don't think that rebasing would work in this case. Please tell me if it doesn't because then I'll make a new pr (with the sign mentioned this time 😅). Sorry for the inconvenience caused.
