### ISSUE TITLE
Incorrect metapath length validation

### ISSUE THREAD

**Issue by n-dusan** [theupdateframework/tuf#2136]
**Description of issue or feature request**:

As per [TUF metapath specification](https://theupdateframework.github.io/specification/latest/#metapath-length), `length` attribute of metadata is an integer numerical value. However, the [current](https://github.com/theupdateframework/python-tuf/blob/28b027815e2e6490c4ec7cc21d8f73373cbe2670/tuf/api/metadata.py#L1055-L1056) validation states that length has to be greater than zero. So I believe this is a slight inconsistency with the specification?

There are legitimate use-cases where signed metadata is an empty file which length is 0. For example, storing git empty files results in their length being 0. 

**Current behavior**:

Signed metadata with length 0 raises a `ValueError('Length must be > 0, got 0')`

**Expected behavior**:

Length can be 0.

**Comment by jku** [comment]
Sounds good otherwise but can you explain more about _"signed metadata is an empty file"_...  As far as I can see zero length does not make a lot of sense for [metapath-length](https://theupdateframework.github.io/specification/latest/#metapath-length): zero length metadata files aren't going to be useful to anyone, or am I mistaken? It does possibly make sense as [targetfile length](https://theupdateframework.github.io/specification/latest/#targets-obj-length) (which is the main use case for length/hashes anyway).  There also does not seem to be any reason to not allow 0 length for both cases just to be spec compliant.

**Comment by n-dusan** [comment]
Thank you. You are correct. I was referring to targetfile length. Empty files with no content can be seen as useful. They contain a name, and their existence can be an indicator of some event in git history. I agree that zero metapath-length is questionable (and not sure if useful). Although the spec refers to numerical values, I think both are seen as potentially being zero?

**Comment by jku** [comment]
Got it. We're in agreement then: zero length _target_ files are potentially useful and allowing zero length in general does not seem harmful.
