### ISSUE TITLE
refactor Metadata._get_role_and_keys()

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2272]
_EDIT: This relates to code in #2165 -- should likely be fixed in that PR_

Looking at `Metadata._get_role_and_keys()` after a while... I did not do a good job of it.

Potential improvement:
* it should return only the keys for the delegated role (instead of all delegated keys and the specific Role). I was probably avoiding unnecessary allocations here but this makes the code harder to read 
* does not have to return the whole role  but does have to return threshold instead
* the method should be public as it's useful in applications as well
* these changes mean some changes in verify_delegate()

Something like this
```python
    def get_keys_and_threshold(self, delegated_role: str) -> Tuple[List[Key], int]:
```

**Comment by lukpueh** [comment]
FYI, I also changed this method in https://github.com/theupdateframework/python-tuf/pull/2246/ to get keys and threshold  from an explicitly passed `Signed` object instead of `self.signed`.

I needed this for a common abstraction of `Metadata` and `Envelope` (dsse) classes, which accesses `self.signed` via getter method, that, in the case of `Envelope`, takes an optional (deserialization) argument.

**Comment by jku** [comment]
That leads to the conclusion that metadata is the wrong location to begin with? I think I might agree with that: Targets and Root objects could both implement a method with the same signature (in effect implementing a hypothetical Delegator Protocol)

**Comment by jku** [comment]
I just tried this and it looks a lot simpler: will fix this in the no-key branch/PR

**Comment by jku** [comment]
closing: this is reviewed as part of #2165
