### ISSUE TITLE
Print expected type instead of its string representation

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#243]
### Observed

Presently, if a user passes an object O other a list to a Schema ListOf object, the error message will print [the string representation S of O](https://github.com/theupdateframework/tuf/blob/3481586c873c05dfb1fcf981d79001f70297200d/tuf/schema.py#L517). Unfortunately, the error message is obscured when the S is large (e.g. O is a set with hundreds of thousands of strings).
### Expected

I think the error message would be just as effective if we simply printed the type of O.

Thanks!

**Comment by joshuagl** [comment]
`Schema` objects were moved to securesystemslib, but this issue is replicated in the new location. 
`ListOf`'s `check_match` prints the `repr()` of the object, not the `type()` see [`schema.py:523`](https://github.com/secure-systems-lab/securesystemslib/blob/4fe51e95b39c9d188141f470aa7c8ed475744ada/securesystemslib/schema.py#L523)

PR #794 was closed without comment, is this change desirable? Or should we just close this issue?

**Comment by trishankatdatadog** [comment]
Moved to [securesystemslib](https://github.com/secure-systems-lab/securesystemslib/issues/194)
