### ISSUE TITLE
Restricted paths are not retroactive

### ISSUE THREAD

**Issue by SantiagoTorres** [theupdateframework/tuf#250]
When a target file is added before a restricted path is assigned to a delegation, the delegation is still able to write metadata about the target. Like this:
1. Create new delegation
2. Add new target to the delegation
3. Add restricted path
4. Write even though the target is outside of the restricted path

Is this expected behavior?

**Comment by vladimir-v-diaz** [comment]
We no longer enforce restricted paths when writing delegated metadata.  Since delegations now resemble a graph, validating the target files specified by a delegated role depends on which delegating role you first interrogate.  In other words, delegated roles must be free to sign for any paths they wish.
