### ISSUE TITLE
ngclient: lots of 404 traffic when trying to update root metadata?

### ISSUE THREAD

**Issue by woodruffw** [theupdateframework/tuf#2730]
Hi folks. I think this is the right place for this issue (since it's observed behavior with the `tuf` Python client), but let me know if it isn't and I'd be happy to move or re-file it.

**Description of issue or feature request**:

PyPI is currently fetching TUF metadata from Sigstore's production TUF repo (<https://tuf-repo-cdn.sigstore.dev/>) as part of the index's implementation of PEP 740.

As part of routine TUF metadata updates, PyPI's admins have noticed a large amount of 404 traffic, including repeated requests for non-existing metadata files (like `11.root.json`, when the latest is `10.root.json`). This doesn't appear to impair the functioning of TUF, but it's causing a lot of traffic alerts.

So, my actual question: is this intended behavior and, if so, do the python-tuf maintainers have thoughts or tips on making integration a bit quieter?

For context, I _think_ this is where the 404s are happening and subsequently get ignored by the client itself:

https://github.com/theupdateframework/python-tuf/blob/42c3b2d919e2cbb2e0b250fedfcb17072e6ef8ab/tuf/ngclient/updater.py#L314-L339

**Current behavior**:

Lots of 404s when updating TUF repo metadata.

**Expected behavior**:

Fewer 404s, possibly.

h/t @miketheman

**Comment by jku** [comment]
> So, my actual question: is this intended behavior and, if so, do the python-tuf maintainers have thoughts or tips on making integration a bit quieter?

Yeah, it's intended. This is what the spec requires: https://theupdateframework.github.io/specification/latest/#update-root

I think the only reasonable way to avoid the 404s is to avoid TUF altogether: I think it's potentially ok for clients to skip the the whole metadata update _if they are confident the artifacts they have are fine_. I think this is an application decision and not something python-tuf is going to do (this is essentially the "offline" discussion we've had before). 

So in this case the sigstore using app could store time-of-last-tuf-update and avoid doing another tuf update _if it's fine with not finding out about trust root changes  that have happened since time-of-last-tuf-update_

This approach of course would not remove the 404s: every TUF update that does happen would still result in a 404. To get around that I think a specification change would be  needed.

**Comment by jku** [comment]
You didn't ask but for completeness: if you're also trying to minimize the timestamp requests (that actually lead to a 200 response), there is a possibility of using etag and `If-None-Match` to move fewer bytes. It is not strictly compliant with the spec and does affect the security very slightly... but I think it might be an acceptable feature that python-tuf could support if there is a real need for it

**Comment by woodruffw** [comment]
Thanks for the detailed response! It makes sense that TUF needs to make those requests as part of its timeliness guarantees, although it's unfortunate that they get surfaced at the logging/integration layer in PyPI.

I asked a bit about that, and it seems like PyPI is surfacing them because `ddtrace` monitors _every_ HTTP API call, regardless of whether it uses exceptional control flow for error handling. So I guess there isn't actually a lot python-tuf can do here, and this is a good reminder as any that I need to switch PyPI over to a single-write, multi-read service model for the Sigstore TUF repo 🙂
