### ISSUE TITLE
Ensure We Do Not Inherit File Permissions For Written Key Files 

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#279]
For example: https://github.com/theupdateframework/tuf/blob/develop/tuf/repository_lib.py#L806

**Comment by lukpueh** [comment]
Based on the date, above link most likely pointed to a call to [TempFile's `move` method](https://github.com/theupdateframework/tuf/blob/6b0d060c48ff408cd93ab7c5be02f38ef4365b16/tuf/repository_lib.py#L806), which was [used to persist files](https://github.com/theupdateframework/tuf/blob/6b0d060c48ff408cd93ab7c5be02f38ef4365b16/tuf/util.py#L213-L237) (here a cryptographic key) to disk,  and has been replaced by  [`securesystemslib.util. persist_temp_file`](https://github.com/secure-systems-lab/securesystemslib/blob/5bd6e1b4a6b9ce5b128d28ae712abefbebfe0a11/securesystemslib/util.py#L98-L129) (in [sslib#181](https://github.com/secure-systems-lab/securesystemslib/pull/181)).

But it is hard to guess what the OP meant by *"do not inherit file permissions"* (maybe use a custom `umask`?), and if so, what umask that should be (probably a restrictive one, since it talks about keys?).

I wonder if this request is still valid, or if this is just not in the scope of TUF.

cc @mnm678, @trishankatdatadog, @JustinCappos

**Comment by mnm678** [comment]
As the method in question has been replaced, I think we can close this issue, and reopen if it becomes an issue with the persist_temp_file method.

**Comment by trishankatdatadog** [comment]
I guess he meant private keys should be written with umask `600`, like how OpenSSH restricts the reading and writing of private keys to the user.

**Comment by lukpueh** [comment]
@trishankatdatadog, do you think it's worth keeping this (now clarified) feature request around? If so I can re-open it on the securesystemslib repo.

**Comment by trishankatdatadog** [comment]
Yes, I think so, please

**Comment by lukpueh** [comment]
Will be fixed in secure-systems-lab/securesystemslib#222
