### ISSUE TITLE
Question: can target metadata be verified lazily?

### ISSUE THREAD

**Issue by edsko** [theupdateframework/tuf#282]
Section 5.1 stipulates: "By comparing the trusted targets from the old trusted metadata with the new metadata, the framework is able to determine which target files have changed. The framework ensures that any target files described in delegated target files are allowed to be provided by the delegated role".

This seems to suggest that all (changed) target metadata files must be verified in the check for updates, rather than checking target metadata more "lazily" as they are used. For instance, suppose a single package is signed incorrectly -- should this mean that the entire check-for-updates process should fail? Or could we delay this check until we actually download this package? The latter seems more desirable from a user friendliness perspective, but I'm not completely sure what the ramifications are for security.

**Comment by vladimir-v-diaz** [comment]
To answer your question, target metadata can and should be verified lazily.  The Python implementation downloads delegated target metadata only when required.

I will update the specification to state more clearly that top-level metadata (`root.json`, `targets.json`, `snapshot.json`, `timestamp.json`) is refreshed separately from the delegated metadata (e.g., `targets/projects/haskell`).  After the updater refreshes the top-level metadata, clients request specific target files to download, which would lazily download any required delegated metadata.

Perhaps the updater [client documentation](https://github.com/theupdateframework/tuf/tree/develop/tuf/client#example-client) can clear things up a bit for now.  I agree that the spec is a bit vague in this regard, so I be updating the spec to fix this.

**Comment by dcoutts** [comment]
Thanks again for this and the the other clarifications. Much appreciated.

**Comment by JustinCappos** [comment]
Okay, one quick correction of the correction.  :)

To allow lazy evaluation to be secure, the snapshot role needs a minor
change to the spec which Vlad is about to make.  The change is that the
snapshot role will include the version number of metadata instead of the
secure hash.  The reason is complicated, but we can share a paper in a few
weeks to explain why if you are interested.

So, yes, definitely implement lazy evaluation.  But you'll need to
implement another minor change too.

**Comment by edsko** [comment]
Yes, please share! (Or even send us a work in progress.)

**Comment by vladimir-v-diaz** [comment]
Delegated metadata that has not been lazily evaluated is vulnerable to rollback attacks if the `timestamp` and `snapshot` roles are compromised.  A rollback attack is when "an attacker presents a software update system with older files than those the client has already seen, causing the client to use files older than those the client knows about."

Suppose that there are two delegated roles available on the repository, roles `A` and `B`.  The client requests a file that is provided by the `A` role, and version 2 of `A` is lazily downloaded and cached.  That is, `B` is not downloaded at all.  If at this point an attacker compromises `timestamp` and `snapshot` and tries to trick the client into installing version 1 of `A`, the attack will not succeed because the client will not accept a version of `A` that is less than the client's currently cached version of 2.  The attacker, however, can trick the client into installing an old version of `B` because the client has not downloaded and cached `B` yet.

One way to prevent rollback attacks against any delegated role provided by the repository is to always download them all.  Unfortunately, this approach will be inefficient for repositories that provide many delegated roles.

Another approach is to include the current version of every delegated role available on the repository in the `snapshot` role.  In the example above, the `snapshot` role would have specified that version 2 of `A` is currently available, and version 3 of `B`.  With this setup, clients may lazily download `A` and not have to worry about rollback attacks against `B` because it would know from the `snapshot` role that version 3 is the latest.

I hope this explains the problem.  Let me know if I should expand my answer.  The paper goes into much more detail, and we'd be happy to share it with your team once we submit it.

**Comment by edsko** [comment]
@vladimir-v-diaz thanks for that information, that makes perfect sense.

**Comment by trishankatdatadog** [comment]
Closed, this is solved by lazy delegation traversal in the specification
