### ISSUE TITLE
Invalid keys in example keystore

### ISSUE THREAD

**Issue by jawi** [theupdateframework/tuf#293]
The encrypted ed25519 keys in `examples/keystore` are invalid, it appears that the iterations count field is encoded as a literal string instead of being a numeric value: it is written as `313030303030` instead of `100000` as the code expects.

**Comment by vladimir-v-diaz** [comment]
Thanks for reporting this issue with the examples.

The examples were last updated 2 years ago.  We have since made changes to the format of our metadata and key files, and will need to regenerate them so the new tools can properly load them.  We are currently working on a 1.0 release that will make further tweaks to the format of metadata and key files, so these examples will be modified once again. 

Note: The examples that are up-to-date and normally tested are located here: https://github.com/theupdateframework/tuf/tree/develop/tests/repository_data/

**Comment by jawi** [comment]
I see, that explains it. Maybe it would be an idea to drop a small README in the examples directory that explains this to others as well.

**Comment by jawi** [comment]
Trying to verify the signatures from the up-to-date examples does not seem to work either: if I take the [root.json](https://github.com/theupdateframework/tuf/blob/develop/tests/repository_data/repository/metadata/root.json) and use the corresponding [public key](https://github.com/theupdateframework/tuf/blob/develop/tests/repository_data/keystore/root_key.pub) I'm not able to verify it correctly. Are these signatures verified in any of the tests?

**Comment by jawi** [comment]
Right, after lots of tinkering and debugging, I found out that the RSASSA-PSS validation should use SHA256 instead of the default SHA1 as hashing algorithm... I'm able to verify the signatures of the examples now.

**Comment by vladimir-v-diaz** [comment]
Sorry, I totally missed your edit to the original question, where you later mention the Java implementation.  I hadn't realized that you were trying to verify signatures with external code.

I'll update specification to clarify that we use SHA256 to generate PSS signatures.  It's mentioned in the docstrings, but its apparently easy to overlook because another project had the same issue.

**Comment by jawi** [comment]
Thanks for the update of the spec. Is there any information about how the ed25519 keys will be stored?

**Comment by vladimir-v-diaz** [comment]
Are you referring to the encrypted key file?  In the reference implementation, the private portion of the Ed25519 key is stored.  Private key information is encrypted in the same way regardless of key type, which by default uses AES-256-CTR-Mode and passwords strengthened with PBKDF2-HMAC-SHA256.  See https://github.com/theupdateframework/tuf/blob/develop/tuf/pyca_crypto_keys.py#L664-L752.  The specification does not dictate how to store and protect key files, and it's really up to the implementation.

In metadata, the public portion of the Ed25519 key is stored.  A public key is 32-bytes long, and hexlified to 64-bytes.  See https://github.com/theupdateframework/tuf/blob/develop/tuf/keys.py#L264-L341

**Comment by jawi** [comment]
Sorry, I should've mentioned that I was curious how to store and protect the private Ed25519 keys. Might I suggest that the spec includes a small paragraphs on the protection of keys, something like you mentioned: "The specification does not dictate how to store and protect key files. Implementations should take care in storing and protecting key files from unauthorized access and use."?

**Comment by vladimir-v-diaz** [comment]
@jawi Thanks for the feedback!
