### ISSUE TITLE
Is TUF required with SSL?

### ISSUE THREAD

**Issue by codefx9** [theupdateframework/tuf#327]
Sorry to ask a very naive question. If Client and update server are running communicating over SSL, do we still need TUF for a repository where only one party can push?

**Comment by vladimir-v-diaz** [comment]
If the update server is compromised, attackers can serve malicious updates because they'd also gain access to the transport layer key(s) available on the server.  TUF is designed to minimize the impact of a server compromise, and would be just as effective if only one party had push access to the repository.

We cover the TLS model in Section 4 of the [Diplomat](https://github.com/theupdateframework/tuf/raw/develop/docs/papers/protect-community-repositories-nsdi2016.pdf) paper.

**Comment by codefx9** [comment]
Thanks for the answer. I understand.
