### ISSUE TITLE
Can't use FUSE filesystems with consistent_snapshot

### ISSUE THREAD

**Issue by codefx9** [theupdateframework/tuf#331]
Hi,
I am using a Google Cloud Storage bucket via gcsfuse as the repository storage. When I try to use consistent_snapshot, I get the following error:

`    repository.write(consistent_snapshot=True)
  File "/usr/local/lib/python2.7/dist-packages/tuf/repository_tool.py", line 277, in write
    consistent_snapshot)
  File "/usr/local/lib/python2.7/dist-packages/tuf/repository_lib.py", line 140, in _generate_and_write_metadata
    consistent_snapshot)
  File "/usr/local/lib/python2.7/dist-packages/tuf/repository_lib.py", line 1520, in generate_targets_metadata
    os.link(target_path, digest_target)
OSError: [Errno 38] Function not implemented`

The issue is gcsfuse does not support hard links. Can consistent_snapshot functionality be implemented without using hard links?

Thanks.

**Comment by vladimir-v-diaz** [comment]
The consistent snapshot functionality can indeed be implemented to make full copies, rather than hard links.  We default to hard linking for efficiency.

If you need to override this behaviour for the time being, there are only 3 instances of `os.link` you'd need to change in the implementation.

https://github.com/theupdateframework/tuf/blob/develop/tuf/repository_lib.py#L1577
https://github.com/theupdateframework/tuf/blob/develop/tuf/repository_lib.py#L1970
https://github.com/theupdateframework/tuf/blob/develop/tuf/repository_lib.py#L2066

You can replace the os.link() calls to instead use one of the shutil.copy* functions: https://docs.python.org/2/library/shutil.html

A more cleaner approach would be to add an option to [tuf/conf.py](https://github.com/theupdateframework/tuf/blob/develop/tuf/conf.py) and allow integrators to set their preferred method of creating consistent snapshots (i.e., hard links, full copies, etc.).

**Comment by JustinCappos** [comment]
Note, the amount of space this takes up may be larger than you want.
However, if the cloud storage technology you are using has a backing store
that does de-duplication, then linking ~= copying.

**Comment by vladimir-v-diaz** [comment]
@codefx9 
We modified the way consistent snapshots are generated, which you may review here: https://github.com/theupdateframework/tuf/blob/develop/tuf/repository_lib.py#L2022-L2064

You now have the option of either creating a copy or a hard link to consistent files.  Thanks for reporting this issue!
