### ISSUE TITLE
Root.json size/hashes in snapshot.json are superfluous

### ISSUE THREAD

**Issue by heartsucker** [theupdateframework/tuf#451]
[From the spec](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L633-L634)

> For the root role, the hash(es), size, and version number are listed.

Since the downloading and verification of the root.json is never done with a dependency on snapshot.json, there is no reason to have these in the metadata.

**Comment by vladimir-v-diaz** [comment]
I think the Timestamp and Snapshot roles can ensure that the Root delivered to the client is indeed the latest version.  Listing Root in Snapshot metadata can help with consistency.

@JustinCappos @trishankkarthik @awwad What do you guys think?

**Comment by awwad** [comment]
In TAP 5, we were planning to remove the expectation that Root is validated by Snapshot anyway. Pinning does involve having custom Root.json files, and these shouldn't be validated by a separate party's Snapshot.

The current security analysis for the removal of root metadata from snapshot is [here](https://github.com/theupdateframework/taps/blob/master/tap5.md#security-analysis). I haven't thought through this version, personally.

**Comment by heartsucker** [comment]
It appears I'm making a redundant observation. :)

**Comment by heartsucker** [comment]
> we do lose the ability to ensure that the Root delivered to the client is the latest version

I'm not sure what the use case here is. If the first step is to download the root metadata, we could only get to this situation if:

1) The snapshot was compromised and is lying
2) There are some N root.json's with version greater than what was received (MITM plays old root as newest, but also doesn't role it back to a version before the one the client knows about)

**Comment by awwad** [comment]
Yes, that's the scenario. It's pretty narrow.

**Comment by heartsucker** [comment]
In that case, could the spec say "it MAY include the size/hash to ensure the correct root was received. Should the root not match these values, the client MAY report the presence of an attack."

**Comment by vladimir-v-diaz** [comment]
> In TAP 5, we were planning to remove the expectation that Root is validated by Snapshot (and so the listing of Root in Snapshot) anyway.

According to TAP 5, Snapshot metadata should continue to list Root for backwards compatibility. (although the mix of shalls and should is confusing, at least to me):
https://github.com/theupdateframework/taps/blob/master/tap5.md#changes-to-the-snapshot-metadata-file

**Comment by trishankkarthik** [comment]
Hello, usual suspects! I was just going to say what @vladimir-v-diaz did :)

I agree that we should clean up the SHALLs and SHOULDs. Vlad, are you up for it?

**Comment by awwad** [comment]
**Requirements:**
What @heartsucker suggests is basically what it should be, both currently and post-TAP5: listing Root in Snapshot or checking Root per Snapshot should be optional.

(I guess we don't really need to worry about changing the current spec on its own as long as TAP 5 is adopted, but as far as I'm concerned, an implementation is not going to be non-conformant just because it doesn't list Root in Snapshot.)

**Backwards compatibility:**
So, there's a semantic issue on backwards compatibility here. _I_ would say that the short version is that TAP 5 is backwards incompatible.
The particulars -- that a new client can process old metadata without security issues, but an old client will be unable to process new metadata that includes URLs or excludes root -- may be worth mentioning in passing and only in the Backwards Compatibility section.

**Editing TAP 5:**
It looks like comments have kinda glommed onto the end of sections over time in a way that makes things contradictory or confusing, yeah.

As a final note, I'm curious about what @JustinCappos thinks and if any thinking on this has changed per the last conversations with CoreOS or Docker.

**Comment by vladimir-v-diaz** [comment]
Issue #13 and [TAP 6: Include specification version identifier in metadata](https://github.com/theupdateframework/taps/issues/35) are relevant to this discussion.

**Comment by heartsucker** [comment]
I think this was addressed by some recent merges. Can we close this?

**Comment by vladimir-v-diaz** [comment]
Yup!
Root's hash and length no longer listed in Snapshot.  Implemented in https://github.com/theupdateframework/tuf/pull/469
