### ISSUE TITLE
compression_algorithms doesn't need to be mandatory

### ISSUE THREAD

**Issue by heartsucker** [theupdateframework/tuf#471]
The spec makes this field mandatory, but it shouldn't. Allowing for compression doesn't have any impact on the security model, and an implementer may choose to have an empty list of algorithms. This makes this field unnecessary.

Related: #431

**Comment by vladimir-v-diaz** [comment]
One option we are considering is the removal of compression from the specification.  It might be better to handle compression at layer 6 of the OSI protocol stack so that data is decompressed as it arrives.

Trying to handle compression in the TUF specification has lead to inconsistent behavior, such as only compressing certain roles, unnecessary complexity, poor protection against decompression bombs, etc.

The Docker folks have been a strong proponent in following down this path.

**Comment by heartsucker** [comment]
I mentioned it a bit in #105 that this is non-trivial. The comments I made there were written with the assumption that compression wasn't leaving the spec. That said, I would side with the Docker kids and say that compression shouldn't be part of the spec. More generally, I think the spec should only include things that are necessary to provide security.

**Comment by vladimir-v-diaz** [comment]
[TAP 10](https://github.com/theupdateframework/taps/blob/master/tap10.md) was implemented in pull request #485, which has been merged.  TUF no longer supports compression of top-level metadata, so the `compression_algorithms` attribute has been removed.
