### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by davedoesdev** [theupdateframework/tuf#530]
Do you have a roadmap towards the next release?

**Comment by vladimir-v-diaz** [comment]
The project really does need a roadmap.  It is also recommended by the CNCF that the project "have a documented roadmap that describes what the project intends to do and not do for at least the next year."

After reviewing the commits that have been merged since the last release, it is apparent that many things have changed.  A new release is definitely warranted.  Our release cycle has been awfully informal, so thanks for encouraging us to put out a roadmap for the community.

I'll work on a new release, and follow up with a proposed roadmap.  The roadmap will likely coincide with the acceptance and implementation of [TAPs](https://github.com/theupdateframework/taps), implementation of new features such a CLI/quickstart tool, and bug/security fixes.

I'll update this issue when the new version is released.

**Comment by davedoesdev** [comment]
@vladimir-v-diaz thanks, appreciate it.

**Comment by vladimir-v-diaz** [comment]
<img width="1255" alt="screen shot 2017-11-10 at 5 07 57 pm" src="https://user-images.githubusercontent.com/3520883/32680697-e2ef2de4-c639-11e7-8755-55fd3fa9ba6d.png">

**Comment by davedoesdev** [comment]
Guess I'll be making some changes to my project then :)

**Comment by vladimir-v-diaz** [comment]
FYI:
https://pypi.python.org/pypi/tuf/0.10.1
https://github.com/theupdateframework/tuf/releases/tag/v0.10.1

**Comment by davedoesdev** [comment]
Thanks, the changes look good. I did a cursory look and I think I'll be able to make https://github.com/davedoesdev/dtuf work with it.

**Comment by vladimir-v-diaz** [comment]
Project roadmap added in #534.
