### ISSUE TITLE
TUF client requests TUF server through proxy

### ISSUE THREAD

**Issue by thangld322** [theupdateframework/tuf#814]
Can TUF handle proxy?
If yes, where can I find a tutorial about handling proxy for TUF client, please?
Thank you!

**Comment by awwad** [comment]
Yes.  PR #781 made sure that TUF had proxy support.  This [test](https://github.com/theupdateframework/tuf/blob/develop/tests/test_proxy_use.py) tests use of tuf through various proxies.  Basically, you just need to set your environment variables to include 'HTTP_PROXY' set to your proxy address (or include 'HTTPS_PROXY' if you're connecting to a middleman proxy via HTTPS).

**Comment by thangld322** [comment]
Thank awwad
This version has not released right? So I gotta clone develop branch and install from that source?

**Comment by awwad** [comment]
First release with that feature: https://github.com/theupdateframework/tuf/releases/tag/v0.11.2.dev1
The most recent release also includes that feature: https://github.com/theupdateframework/tuf/releases/tag/v0.11.2.dev2

These are development releases due to the sacrifice of the slow retrieval attack protection.
