### ISSUE TITLE
NoWorkingMirrorError swallows error messages

### ISSUE THREAD

**Issue by therve** [theupdateframework/tuf#857]
**Description of issue**:

When tuf raises a NoWorkingMirrorError, it displays the list of URLs with the corresponding exception classes, but the error message of each exception is lost.

**Current behavior**:

I got the following error in some logs:

```
tuf.exceptions.NoWorkingMirrorError: No working mirror was found:
  'xxx': ReplayedMetadataError()
```

You can reproduce the issue easily with the following script:

```
import tuf.exceptions

error = tuf.exceptions.ReplayedMetadataError('myrole', '1.2.3', '1.2.1')
print(str(error))
mirror_error = tuf.exceptions.NoWorkingMirrorError({'myurl': error})
print(str(mirror_error))
````

Which outputs:

```
Downloaded 'myrole' is older ('1.2.3') than the version currently installed ('1.2.1').
No working mirror was found:
  '': ReplayedMetadataError()
```

**Expected behavior**:

I want to get the actual content of ReplayedMetadataError.

**Comment by adityasaky** [comment]
Hello!

This seems like a very straightforward fix:

https://github.com/theupdateframework/tuf/blob/develop/tuf/exceptions.py#L247

`repr(mirror_error) -> str(mirror_error)`

Which gives me:

```>>> import tuf.exceptions
>>> error = tuf.exceptions.ReplayedMetadataError('myrole', '1.2.3', '1.2.1')
>>> print(str(error))
Downloaded 'myrole' is older ('1.2.3') than the version currently installed ('1.2.1').
>>> mirror_error = tuf.exceptions.NoWorkingMirrorError({'myurl': error})
>>> print(str(mirror_error))
No working mirror was found:
  '': Downloaded 'myrole' is older ('1.2.3') than the version currently installed ('1.2.1').
```

**Comment by trishankatdatadog** [comment]
Ah, @therve is one of us at Datadog, thanks for helping out :)

**Comment by adityasaky** [comment]
No problem!

**Comment by awwad** [comment]
That actually won't fix the missing information in the logs, in part because `updater`'s loggers don't call `str()` on `NoWorkingMirrorError`, so changing `NoWorkingMirrorError.__str__()` won't fix it.  Example logging [here](https://github.com/theupdateframework/tuf/blob/b005002fef3d6fa679ed77878b248b7d65876083/tuf/client/updater.py#L1558-L1559).

This problem is basically a result of some fancy exception classes that have calculated error messages produced by `__str__()`, but no `__repr__()` methods.  When those (`ReplayedMetadataError`, `BadHashError`, some others) are put in a `NoWorkingMirrorError`, the calculated messages don't show up in the logs.  Others, like `BadVersionNumberError`, still show up fine in logs (or a script like the above) when they're put into a `NoWorkingMirrorError`.

The easiest fix here is probably one of these options:
1. change `NoWorkingMirrorError.__str__()` as @adityasaky suggests, and also change all the `logger.error()` calls to both mention the particular exception types and then call `str()` (since otherwise you'd lose the individual exception types in the logs)
2. or add a `__repr__()` method to `ReplayedMetadataError` and similar exceptions

I think the pythonic answer is probably **2**, since ``repr()`` is intended for this kind of debugging.

**Comment by awwad** [comment]
@therve #859 seems to resolve the issue.  If you happen to be encountering this and it's in your way, feel free to try it out.  Should be reviewed and merged soon.

```
[2019-04-19 17:39:56,710 UTC] [tuf.client.updater] [ERROR] [_get_metadata_file:1559@updater.py]
Failed to update 'timestamp.json' from all mirrors: {'http://localhost:33283/tmpj3hx5_qv/TestReplayAttack__u7ayn0g/repository/metadata/timestamp.json': ReplayedMetadataError : Downloaded 'timestamp' is older (1) than the version currently installed (2).}
```

**Comment by trishankatdatadog** [comment]
The real mystery is why we are seeing these alleged ReplayedMetadataErrors in our tests in the first place...
