### ISSUE TITLE
One way to open, read, write and close files

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#87]
Presently, we have many ways to open, read, write and close files. Sometimes we use the Python built-in functions, and sometimes else we use our own file-like objects.

This makes it harder to easily adapt the code to changing requirements. (For example, I cannot easily add code to compress or decompress files and assume that it will work everywhere.)

I think we should design one file-like object to serve our needs and use that everywhere in the code.

**Comment by lukpueh** [comment]
- https://github.com/secure-systems-lab/securesystemslib/issues/180#issuecomment-530873492 advocates for not having a custom *File-not-file* class.
- https://github.com/theupdateframework/tuf/pull/918 and https://github.com/secure-systems-lab/securesystemslib/pull/181 removes TUF's custom file-like `TempFile` implementation, and adds a single `persist_temp_file` utility function.
- https://github.com/theupdateframework/tuf/pull/485 removes native support for compressed top-level metadata (tap 10).

Let's close due to inactivity.
