### ISSUE TITLE
Optional upper bound on targets file sizes?

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#968]
**Description of issue or feature request**:

Provide an option to set upper bound on targets file sizes.

**Current behavior**:

Right now, we have [upper bounds](https://github.com/theupdateframework/tuf/blob/530d4a8eef7082d6bcbae6f163bda80b37714893/tuf/settings.py) on metadata file sizes. However, we have none for targets file sizes themselves.

**Expected behavior**:

Some users, such as on embedded systems, may want an option to not accept large enough targets files.

**Comment by lukpueh** [comment]
For clarification, as per the TUF spec a client must use the `length` specified in targets metadata as upper bound, when downloading target files. This is done to protect against endless-data attacks, and is implemented in the reference implementation.

IIUC, @trishankatdatadog here requests an option that a client can use to override the supposedly benign file size presented by the repository, e.g. in order to satisfy local requirements.

**Comment by jku** [comment]
I would suggest this is a client application decision that does not require new options.

ngclient example (legacy should work about as well):
```python
info = updater.get_targetinfo("file.txt")
if info.length > DOWNLOAD_SIZE_LIMIT:
   raise DownloadTooLargeError
path = updater.download_target(info) 
```

**Comment by jku** [comment]
I'm closing this. I don't think adding configuration to ngclient is out of the question but previous comment stands: it's easy to implement in the client itself.
